Default: 0
Slime: 1
MagmaCube: 1
Zombie: 2
Spider: 2
Skeleton: 3
Piglin: 3
SkeletonHorse: 3
Silverfish: 3
Endermite: 3
Phantom: 3
Pillager: 3
Vindicator: 3
PigZombie: 3
Creeper: 4
Witch: 4
Zoglin: 4
Guardian: 4
Enderman: 5
Blaze: 5
WitherSkeleton: 5
Shulker: 5
PiglinBrute: 5
Vex: 20
Ravager: 20
Evoker: 20
ElderGuardian: 50
EnderDragon: 150
Wither: 200
Warden: 200

