name: SMP5
version: '${project.version}'
main: com.stiggles.smp5.main.SMP5
api-version: 1.19
depend: [Citizens]
commands:
  loadcitizens:
    description: Init Citizens
  world:
    description: Teleports the player to the specified world.
  start-dungeon:
    description: Teleports the player to the dungeon and begins the event.
