name: SMP5
version: '${project.version}'
main: com.stiggles.smp5.main.SMP5
api-version: 1.19
depend: [Citizens]
commands:
  loadcitizens:
    description: Init Citizens
  world:
    description: Teleports the player to the specified world.
  start-dungeon:
    description: Teleports the player to the dungeon and begins the event.
  coins:
    description: Displays the amount of coins you currently have
    aliases: c
  togglecoin:
    description: Toggles the reward message for killing mobs on/off
    aliases: tc
  o:
    description: Open/close the server for admin access only.
  smm:
    description: For admin use only
  get-items:
    description: Admin only
  alert:
    description: Admins only!
  reset-merchants:
    description: Admins only!